"""
macro_lens.py — LangGraph orchestration pipeline for macro-lens v4.

Architecture (v4 hybrid quant/AI):
  data_fetcher          → fetches FRED indicators + VIX for live display
  quant_regime_node     → RegimeHMMEngine classifies growth/inflation regime
  llm_regime_validator  → optional: gates + LLM sanity check on HMM output
  quant_allocation_node → Black-Litterman generates tactical weights
  weight_calculator     → normalises weights to sum to 1.0 (safety net)
  narrative_generator   → LLM writes human-readable rationale (live mode only)
  reporter              → formats the final report string

v4 changes vs v3:
  - RegimeHMMEngine accepts use_cfnai_ma3 flag (passed through run_backtest /
    run_analysis via engine construction)
  - llm_regime_validator node added between quant_regime_node and
    quant_allocation_node; controlled by validate_regime parameter on
    build_graph() and run_backtest()
  - MacroState extended with four validator fields
  - reporter updated to show validator decision when present
  - run_backtest() accepts validate_regime and use_cfnai_ma3 arguments

validate_regime modes:
  "off"    — validator node not added to graph; zero overhead (default in backtest)
  "log"    — validator runs and writes decision to state fields, but does NOT
             modify regime or regime_confidence; weights unchanged vs "off"
  "active" — validator runs; OVERRIDE replaces regime in state; FLAG sets
             regime_confidence to 0.25 (forces BL toward policy weights)

Three-arm experiment:
  Arm 1: run_backtest(validate_regime="off",    use_cfnai_ma3=True)  — structural fixes baseline
  Arm 2: run_backtest(validate_regime="log",    use_cfnai_ma3=True)  — advisory log only
  Arm 3: run_backtest(validate_regime="active", use_cfnai_ma3=True)  — active override

Run Arm 2 before Arm 3 — it populates validator_cache.json so Arm 3 is all cache hits.
"""

import socket
socket.setdefaulttimeout(10)

import os
import json
import hashlib
from pathlib import Path
from fredapi import Fred
import yfinance as yf
import pandas as pd
from dotenv import load_dotenv

from typing import Annotated, Optional, Dict, Any, List
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from datetime import datetime, timedelta

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

import time
import uuid
import concurrent.futures
from collections import defaultdict
import numpy as np
from tenacity import retry, wait_exponential, stop_after_attempt

from hmm_models import RegimeHMMEngine
from black_litterman import generate_target_weights, ASSETS as BL_ASSETS
from validator_prompt_FROZEN import (
    PROMPT_VERSION,
    SYSTEM_PROMPT,
    should_invoke_validator,
    build_blinded_input,
    build_user_prompt,
    build_cache_key,
    parse_validator_response,
    audit_rationale_for_contamination,
)

load_dotenv(override=True)


# ---------------------------------------------------------------------------
# LangGraph state schema
# ---------------------------------------------------------------------------

class MacroState(TypedDict):
    # Meta
    current_date: str
    observation_date: Optional[str]

    # FRED indicators (live mode only; None in backtest)
    macro_data: Optional[Dict[str, Any]]
    fetch_attempts: int
    data_requests: Optional[List[str]]

    # Regime — classified by HMM (not LLM)
    growth_direction: Optional[str]
    inflation_direction: Optional[str]
    regime: Optional[str]
    regime_confidence: Optional[float]
    regime_rationale: Optional[str]
    previous_regime: Optional[str]
    hmm_probabilities: Optional[Dict[str, float]]

    # v4: validator fields
    original_hmm_regime: Optional[str]          # pre-override regime, for audit trail
    regime_validator_decision: Optional[str]     # CONFIRM / FLAG / OVERRIDE / SKIPPED
    regime_validator_rationale: Optional[str]    # LLM rationale string
    pcepilfe_level: Optional[float]              # raw PCE YoY decimal

    # Allocation — generated by BL (not LLM)
    tilts: Optional[Dict[str, str]]
    weights: Optional[Dict[str, float]]
    allocation_rationale: Optional[str]

    # Output
    report: Optional[str]
    messages: Annotated[List[Any], add_messages]

    # Backtest bookkeeping
    history_dates: Optional[List[str]]


# ---------------------------------------------------------------------------
# FRED series for live dashboard display
# ---------------------------------------------------------------------------

PRIMARY_SERIES = {
    "t10y2y":       "T10Y2Y",
    "bamlh0a0hym2": "BAMLH0A0HYM2",
    "t10yie":       "T10YIE",
    "pcepilfe":     "PCEPILFE",
    "cfnai":        "CFNAI",
    "sahmrealtime": "SAHMREALTIME",
    "unrate":       "UNRATE",
    "stlfsi4":      "STLFSI4",
}

SECONDARY_SERIES = {
    "cpiaucsl": "CPIAUCSL",
    "permit":   "PERMIT",
    "umcsent":  "UMCSENT",
}


# ---------------------------------------------------------------------------
# ETF proxies and policy weights
# ---------------------------------------------------------------------------

ASSET_PROXIES = {
    "equities":         "SPY",
    "bonds":            "TLT",
    "inflation_linked": "TIP",
    "commodities":      "GSG",
    "gold":             "GLD",
    "cash":             "BIL",
}

BASELINE_WEIGHTS = {
    "equities":         0.40,
    "bonds":            0.30,
    "inflation_linked": 0.10,
    "commodities":      0.08,
    "gold":             0.07,
    "cash":             0.05,
}

COV_WINDOW_MONTHS = 60

# Path for validator decision cache — separate from zscore_cache.json
VALIDATOR_CACHE_PATH = Path("validator_cache.json")


# ---------------------------------------------------------------------------
# Validator cache helpers
# ---------------------------------------------------------------------------

def _load_validator_cache() -> Dict[str, dict]:
    """Load validator decision cache from disk."""
    if not VALIDATOR_CACHE_PATH.exists():
        return {}
    with open(VALIDATOR_CACHE_PATH, "r") as f:
        return json.load(f)


def _save_validator_cache(cache: Dict[str, dict]) -> None:
    """Persist validator decision cache to disk."""
    with open(VALIDATOR_CACHE_PATH, "w") as f:
        json.dump(cache, f, indent=2)


# ---------------------------------------------------------------------------
# FRED fetch helpers (unchanged from v3)
# ---------------------------------------------------------------------------

def fetch_fred_series(fred: Fred, series_id: str, observation_date: Optional[str] = None) -> dict:
    try:
        def _fetch():
            if observation_date:
                start_date = (
                    datetime.strptime(observation_date, "%Y-%m-%d") - timedelta(days=365)
                ).strftime("%Y-%m-%d")
                return fred.get_series(
                    series_id,
                    observation_start=start_date,
                    observation_end=observation_date,
                    realtime_start=observation_date,
                    realtime_end=observation_date,
                )
            else:
                start_date = (datetime.now() - timedelta(days=365)).strftime("%Y-%m-%d")
                return fred.get_series(series_id, observation_start=start_date)

        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_fetch)
            data = future.result(timeout=15)

        data = data.dropna()
        if len(data) == 0:
            return {"error": "no data"}

        latest     = float(data.iloc[-1])
        previous   = float(data.iloc[-2]) if len(data) >= 2 else None
        mom_change = round(latest - previous, 4) if previous is not None else None

        return {
            "latest":   round(latest, 4),
            "previous": round(previous, 4) if previous else None,
            "change":   mom_change,
            "date":     str(data.index[-1].date()),
        }
    except concurrent.futures.TimeoutError:
        return {"error": f"timeout fetching {series_id}"}
    except Exception as e:
        return {"error": str(e)}


def fetch_vix(observation_date: Optional[str] = None) -> dict:
    try:
        vix = yf.Ticker("^VIX")
        if observation_date:
            end_dt   = datetime.strptime(observation_date, "%Y-%m-%d")
            start_dt = end_dt - timedelta(days=10)
            hist = vix.history(
                start=start_dt.strftime("%Y-%m-%d"),
                end=(end_dt + timedelta(days=1)).strftime("%Y-%m-%d"),
            )
        else:
            hist = vix.history(period="5d")

        if hist.empty:
            return {"error": "no data"}

        latest   = round(float(hist["Close"].iloc[-1]), 2)
        previous = round(float(hist["Close"].iloc[-2]), 2) if len(hist) >= 2 else None
        return {
            "latest":   latest,
            "previous": previous,
            "change":   round(latest - previous, 2) if previous else None,
            "date":     str(hist.index[-1].date()),
        }
    except Exception as e:
        return {"error": str(e)}


def data_fetcher(state: MacroState) -> dict:
    fred = Fred(api_key=os.getenv("FRED_API_KEY"))
    fetch_attempts   = state.get("fetch_attempts", 0)
    observation_date = state.get("observation_date")

    series_to_fetch = PRIMARY_SERIES.copy()
    if fetch_attempts > 0:
        series_to_fetch.update(SECONDARY_SERIES)

    macro_data = {}
    for key, series_id in series_to_fetch.items():
        macro_data[key] = fetch_fred_series(fred, series_id, observation_date)

    macro_data["vix"] = fetch_vix(observation_date)

    return {
        "macro_data":     macro_data,
        "fetch_attempts": fetch_attempts + 1,
    }


# ---------------------------------------------------------------------------
# ETF price helpers (unchanged from v3)
# ---------------------------------------------------------------------------

def _fetch_price_history(tickers: List[str], start: str, end: str) -> pd.DataFrame:
    raw = yf.download(
        tickers,
        start=start,
        end=(datetime.strptime(end, "%Y-%m-%d") + timedelta(days=5)).strftime("%Y-%m-%d"),
        interval="1mo",
        auto_adjust=True,
        progress=False,
    )
    if isinstance(raw.columns, pd.MultiIndex):
        prices = raw["Close"]
    else:
        prices = raw[["Close"]] if "Close" in raw.columns else raw

    return prices.ffill().dropna(how="all")


def _monthly_dates(start: str = "2010-01-01", end: Optional[str] = None) -> List[str]:
    start_dt = datetime.strptime(start, "%Y-%m-%d")
    end_dt   = datetime.strptime(end, "%Y-%m-%d") if end else datetime.today()

    dates   = []
    current = start_dt.replace(day=1)
    while current <= end_dt:
        if current.month == 12:
            last_day = current.replace(day=31)
        else:
            last_day = current.replace(month=current.month + 1, day=1) - timedelta(days=1)
        if last_day > end_dt:
            last_day = end_dt
        dates.append(last_day.strftime("%Y-%m-%d"))
        if current.month == 12:
            current = current.replace(year=current.year + 1, month=1)
        else:
            current = current.replace(month=current.month + 1)

    return dates


# ---------------------------------------------------------------------------
# Performance computation (unchanged from v3)
# ---------------------------------------------------------------------------

def _compute_performance(monthly_records: list, monthly_returns: pd.DataFrame) -> dict:
    portfolio_returns = []
    benchmark_returns = []
    policy_returns    = []
    perf_dates        = []

    policy_w = {"SPY": 0.40, "TLT": 0.30, "TIP": 0.10,
                "GSG": 0.08, "GLD": 0.07, "BIL": 0.05}

    for i, record in enumerate(monthly_records[:-1]):
        next_date_str = monthly_records[i + 1]["date"]
        next_dt       = pd.Timestamp(next_date_str)

        ret_idx = monthly_returns.index
        mask    = (ret_idx.year == next_dt.year) & (ret_idx.month == next_dt.month)
        if not mask.any():
            continue

        ret_row  = monthly_returns[mask].iloc[0]
        w        = record["weights"]

        port_ret = sum(
            w.get(asset, 0.0) * float(ret_row[ticker])
            for asset, ticker in ASSET_PROXIES.items()
            if ticker in ret_row.index and not pd.isna(ret_row[ticker])
        )

        spy_ret   = float(ret_row["SPY"]) if "SPY" in ret_row.index and not pd.isna(ret_row["SPY"]) else 0.0
        tlt_ret   = float(ret_row["TLT"]) if "TLT" in ret_row.index and not pd.isna(ret_row["TLT"]) else 0.0
        bench_ret = 0.60 * spy_ret + 0.40 * tlt_ret

        pol_ret = sum(
            pw * float(ret_row[ticker])
            for ticker, pw in policy_w.items()
            if ticker in ret_row.index and not pd.isna(ret_row[ticker])
        )

        portfolio_returns.append(port_ret)
        benchmark_returns.append(bench_ret)
        policy_returns.append(pol_ret)
        perf_dates.append(next_dt)

    port_series   = pd.Series(portfolio_returns, index=perf_dates)
    bench_series  = pd.Series(benchmark_returns, index=perf_dates)
    policy_series = pd.Series(policy_returns,    index=perf_dates)

    equity_curve    = (1 + port_series).cumprod()   * 100
    benchmark_curve = (1 + bench_series).cumprod()  * 100
    policy_curve    = (1 + policy_series).cumprod() * 100

    def max_drawdown(curve: pd.Series) -> float:
        rolling_max = curve.cummax()
        return float(((curve - rolling_max) / rolling_max).min())

    def sharpe(returns: pd.Series, rf: float = 0.02) -> float:
        ann_ret = (1 + returns.mean()) ** 12 - 1
        ann_vol = returns.std() * (12 ** 0.5)
        return (ann_ret - rf) / ann_vol if ann_vol > 0 else float("nan")

    n_months = len(port_series)
    n_years  = n_months / 12 if n_months > 0 else 1

    total_ret_port   = float((equity_curve.iloc[-1]   / 100) - 1)
    total_ret_bench  = float((benchmark_curve.iloc[-1] / 100) - 1)
    total_ret_policy = float((policy_curve.iloc[-1]    / 100) - 1)

    print("\n=== Benchmark Comparison ===")
    print(f"{'Metric':<25} {'Macro-Lens':>12} {'Policy Mix':>12} {'60/40':>12}")
    print("-" * 63)
    print(f"{'Total Return':<25} {total_ret_port:>11.1%} {total_ret_policy:>11.1%} {total_ret_bench:>11.1%}")
    print(f"{'Ann. Return':<25} {float((1+total_ret_port)**(1/n_years)-1):>11.1%} "
          f"{float((1+total_ret_policy)**(1/n_years)-1):>11.1%} "
          f"{float((1+total_ret_bench)**(1/n_years)-1):>11.1%}")
    print(f"{'Sharpe':<25} {sharpe(port_series):>12.2f} {sharpe(policy_series):>12.2f} {sharpe(bench_series):>12.2f}")
    print(f"{'Max Drawdown':<25} {max_drawdown(equity_curve):>11.1%} "
          f"{max_drawdown(policy_curve):>11.1%} "
          f"{max_drawdown(benchmark_curve):>11.1%}")
    print(f"{'Info Ratio vs Policy':<25} {sharpe(port_series - policy_series):>12.2f}")

    return {
        "equity_curve":    equity_curve,
        "benchmark_curve": benchmark_curve,
        "policy_curve":    policy_curve,
        "metrics": {
            "sharpe_portfolio":        sharpe(port_series),
            "sharpe_benchmark":        sharpe(bench_series),
            "sharpe_policy":           sharpe(policy_series),
            "max_drawdown_portfolio":  max_drawdown(equity_curve),
            "max_drawdown_benchmark":  max_drawdown(benchmark_curve),
            "max_drawdown_policy":     max_drawdown(policy_curve),
            "total_return_portfolio":  total_ret_port,
            "total_return_benchmark":  total_ret_bench,
            "total_return_policy":     total_ret_policy,
            "ann_return_portfolio":    float((1 + total_ret_port)  ** (1 / n_years) - 1),
            "ann_return_benchmark":    float((1 + total_ret_bench) ** (1 / n_years) - 1),
            "ann_return_policy":       float((1 + total_ret_policy) ** (1 / n_years) - 1),
            "n_months":                n_months,
        },
    }


# ---------------------------------------------------------------------------
# Shared nodes (outside build_graph — no closure needed)
# ---------------------------------------------------------------------------

def weight_calculator(state: MacroState) -> dict:
    weights = state.get("weights", {})
    if not weights:
        return {"weights": BASELINE_WEIGHTS.copy()}

    weights  = {k: max(0.0, v) for k, v in weights.items()}
    total    = sum(weights.values())
    if total <= 0:
        return {"weights": BASELINE_WEIGHTS.copy()}

    weights  = {k: round(v / total, 4) for k, v in weights.items()}
    residual = round(1.0 - sum(weights.values()), 4)
    if residual != 0.0:
        largest = max(weights, key=weights.get)
        weights[largest] = round(weights[largest] + residual, 4)

    return {"weights": weights}


def reporter(state: MacroState) -> dict:
    weights   = state.get("weights", {})
    hmm_probs = state.get("hmm_probabilities", {})

    weights_text = "\n".join(
        f"  {asset.replace('_', ' ').title():<22} {weight:.1%}"
        for asset, weight in weights.items()
    )

    macro_data = state.get("macro_data") or {}

    def safe_ind(name: str, key: str) -> str:
        if not macro_data:
            return f"  {name:<25} [Not fetched in backtest mode]"
        data = macro_data.get(key, {})
        if "error" in data:
            return f"  {name:<25} [Fetch Error/Unavailable]"
        latest     = data.get("latest")
        change     = data.get("change")
        latest_str = f"{latest:>8.2f}" if latest is not None else "     N/A"
        change_str = f"{change:>+.2f}" if change is not None else " N/A"
        return f"  {name:<25} {latest_str}  (chg: {change_str})"

    probs_text = "\n".join(
        f"  {regime:<35} {prob:.1%}"
        for regime, prob in hmm_probs.items()
    ) if hmm_probs else "  N/A"

    # Validator section — only shown when validator was active
    validator_decision = state.get("regime_validator_decision")
    original_regime    = state.get("original_hmm_regime")

    if validator_decision and validator_decision != "SKIPPED":
        validator_text = (
            f"\nVALIDATOR  [LLM Gate — {PROMPT_VERSION}]\n"
            f"{'─' * 20}\n"
            f"Decision:       {validator_decision}\n"
        )
        if original_regime and original_regime != state.get("regime"):
            validator_text += f"Original HMM:   {original_regime}\n"
            validator_text += f"Overridden to:  {state.get('regime')}\n"
        rationale = state.get("regime_validator_rationale", "")
        if rationale:
            validator_text += f"Rationale:      {rationale}\n"
    else:
        validator_text = ""

    report = f"""
╔══════════════════════════════════════════════════════╗
║           MACRO-LENS REGIME REPORT  (v4)             ║
║           {state['current_date']:<42} ║
╚══════════════════════════════════════════════════════╝

MACRO REGIME  [HMM]
────────────
Regime:      {state.get('regime', 'Unknown')}
Growth:      {str(state.get('growth_direction')).title()}
Inflation:   {str(state.get('inflation_direction')).title()}
Confidence:  {state.get('regime_confidence', 0.0):.1%}
{validator_text}
JOINT REGIME PROBABILITIES
──────────────────────────
{probs_text}

REGIME RATIONALE  [LLM Analyst]
────────────────
{state.get('regime_rationale', 'N/A')}

KEY INDICATORS
──────────────
{safe_ind('Yield curve (T10Y2Y)', 't10y2y')}
{safe_ind('HY spread (BAMLH)', 'bamlh0a0hym2')}
{safe_ind('Breakeven inf (T10YIE)', 't10yie')}
{safe_ind('Core PCE', 'pcepilfe')}
{safe_ind('CFNAI (activity index)', 'cfnai')}
{safe_ind('Sahm rule', 'sahmrealtime')}
{safe_ind('VIX', 'vix')}

TACTICAL ALLOCATION  [Black-Litterman]
───────────────────
{weights_text}

ALLOCATION RATIONALE  [LLM Analyst]
────────────────────
{state.get('allocation_rationale', 'N/A')}
""".strip()

    return {"report": report}


# ---------------------------------------------------------------------------
# LangGraph pipeline factory
# ---------------------------------------------------------------------------

def build_graph(
    engine: RegimeHMMEngine,
    returns_df: pd.DataFrame,
    skip_narrative: bool = False,
    skip_fred: bool = False,
    validate_regime: str = "off",
):
    """
    Build and compile the LangGraph pipeline.

    v4 parameter:
        validate_regime: "off" | "log" | "active"
            "off"    — validator node not wired in; zero overhead
            "log"    — validator runs, writes to state fields, does NOT
                       modify regime or regime_confidence
            "active" — validator runs; OVERRIDE replaces regime;
                       FLAG sets regime_confidence to 0.25

    Graph topology:
      Backtest (skip_fred=True, skip_narrative=True):
        quant_regime_node → [llm_regime_validator] → quant_allocation_node
        → weight_calculator → reporter

      Live:
        data_fetcher → quant_regime_node → [llm_regime_validator]
        → quant_allocation_node → weight_calculator
        → narrative_generator → reporter
    """
    assert validate_regime in ("off", "log", "active"), (
        f"validate_regime must be 'off', 'log', or 'active', got {validate_regime!r}"
    )

    memory = MemorySaver()

    # Load validator cache once per graph build — shared across all monthly steps
    validator_cache: Dict[str, dict] = (
        _load_validator_cache() if validate_regime != "off" else {}
    )

    # ------------------------------------------------------------------
    def quant_regime_node(state: MacroState) -> dict:
        """Classify the macro regime via RegimeHMMEngine."""
        observation_date = state.get("observation_date") or state["current_date"]

        try:
            result = engine.infer(observation_date)
        except ValueError as e:
            print(f"  HMM insufficient history for {observation_date}: {e}")
            return {
                "regime":               "Low Growth / Low Inflation",
                "regime_confidence":    0.25,
                "growth_direction":     "falling",
                "inflation_direction":  "falling",
                "hmm_probabilities": {
                    "High Growth / High Inflation": 0.25,
                    "High Growth / Low Inflation":  0.25,
                    "Low Growth / High Inflation":  0.25,
                    "Low Growth / Low Inflation":   0.25,
                },
                "pcepilfe_level":              None,
                "regime_validator_decision":   "SKIPPED",
                "regime_validator_rationale":  None,
                "original_hmm_regime":         None,
            }

        if "error" in result:
            print(f"  HMM error for {observation_date}: {result['error']}")
            return {
                "regime":               "Low Growth / Low Inflation",
                "regime_confidence":    0.25,
                "growth_direction":     "falling",
                "inflation_direction":  "falling",
                "hmm_probabilities":    {},
                "pcepilfe_level":              None,
                "regime_validator_decision":   "SKIPPED",
                "regime_validator_rationale":  None,
                "original_hmm_regime":         None,
            }

        dominant    = result["dominant_regime"]
        confidence  = result["confidence"]
        joint_probs = result["joint_probabilities"]
        indicators  = result.get("indicators", {})

        return {
            "regime":               dominant,
            "regime_confidence":    confidence,
            "growth_direction":     "rising" if result["growth_high_prob"] >= 0.5 else "falling",
            "inflation_direction":  "rising" if result["inflation_high_prob"] >= 0.5 else "falling",
            "hmm_probabilities":    joint_probs,
            "previous_regime":      dominant,
            "pcepilfe_level":       indicators.get("pcepilfe_level"),
            # Pre-populate validator fields as SKIPPED — overwritten by
            # llm_regime_validator if the node is wired in
            "regime_validator_decision":  "SKIPPED",
            "regime_validator_rationale": None,
            "original_hmm_regime":        None,
        }

    # ------------------------------------------------------------------
    def llm_regime_validator(state: MacroState) -> dict:
        """
        Optional LangGraph node: gated LLM sanity check on HMM output.

        Gate logic (deterministic, from validator_prompt_FROZEN.py):
          Gate 1 — HMM confidence < 0.65
          Gate 2 — PCE YoY > 2.5% but HMM calls Low Inflation
          Gate 3 — VIX > 35 but HMM calls High Growth

        If no gate fires, returns immediately with decision=SKIPPED.
        If any gate fires, builds blinded input (no calendar date), checks
        validator_cache, and calls gpt-4o-mini on cache miss.

        In "log" mode:  writes decision to state, does not alter regime/confidence.
        In "active" mode: OVERRIDE replaces regime; FLAG sets confidence to 0.25.

        The validator_cache is shared across all monthly steps via closure.
        Cache key = SHA-256 of blinded input dict (not observation date).
        """
        observation_date  = state.get("observation_date") or state["current_date"]
        hmm_regime        = state.get("regime", "Low Growth / Low Inflation")
        hmm_confidence    = state.get("regime_confidence", 0.25)
        hmm_probs         = state.get("hmm_probabilities", {})
        pcepilfe_level    = state.get("pcepilfe_level") or 0.0
        macro_data        = state.get("macro_data") or {}

        # Extract growth/inflation call from dominant regime string
        hmm_inflation_call = (
            "High Inflation" if "High Inflation" in hmm_regime else "Low Inflation"
        )
        hmm_growth_call = (
            "High Growth" if "High Growth" in hmm_regime else "Low Growth"
        )

        # VIX: from macro_data if available (live mode), else NaN (backtest)
        vix_level = 0.0
        if macro_data:
            vix_data = macro_data.get("vix", {})
            if "latest" in vix_data:
                vix_level = float(vix_data["latest"])

        # Gate check — deterministic, no LLM involved
        should_invoke, gates_fired = should_invoke_validator(
            hmm_confidence=hmm_confidence,
            pcepilfe_level=pcepilfe_level,
            hmm_inflation_call=hmm_inflation_call,
            vix_level=vix_level,
            hmm_growth_call=hmm_growth_call,
        )

        if not should_invoke:
            return {
                "regime_validator_decision":  "SKIPPED",
                "regime_validator_rationale": None,
                "original_hmm_regime":        None,
            }

        # Build blinded input — no calendar date passed
        # z-scores come from HMM indicators if available, else NaN
        # In backtest without live FRED fetch, HY spread and yield curve
        # are unavailable; pass 0.0 so gates still work but LLM sees zeros
        hy_spread   = 0.0
        yield_curve = 0.0
        if macro_data:
            hy_data  = macro_data.get("bamlh0a0hym2", {})
            yc_data  = macro_data.get("t10y2y", {})
            if "latest" in hy_data:
                hy_spread   = float(hy_data["latest"])
            if "latest" in yc_data:
                yield_curve = float(yc_data["latest"])

        # Pull z-scores from hmm engine result stored in state
        # These were written by quant_regime_node via the indicators dict
        # We re-read them from the engine cache via state — they're always
        # available because infer() populates indicators regardless of mode
        cfnai_zscore    = 0.0
        unrate_zscore   = 0.0
        pcepilfe_zscore = 0.0
        cpiaucsl_zscore = 0.0
        # Access engine cache directly (engine is closed over in build_graph)
        primary_growth_key = engine.growth_features[0]
        cfnai_zscore    = engine.cache.get((primary_growth_key, observation_date), 0.0) or 0.0
        unrate_zscore   = engine.cache.get(("UNRATE",    observation_date), 0.0) or 0.0
        pcepilfe_zscore = engine.cache.get(("PCEPILFE",  observation_date), 0.0) or 0.0
        cpiaucsl_zscore = engine.cache.get(("CPIAUCSL",  observation_date), 0.0) or 0.0

        blinded = build_blinded_input(
            hmm_dominant_regime    = hmm_regime,
            hmm_confidence         = hmm_confidence,
            hmm_joint_probabilities= hmm_probs,
            growth_high_prob       = hmm_probs.get("High Growth / High Inflation", 0.0)
                                   + hmm_probs.get("High Growth / Low Inflation", 0.0),
            inflation_high_prob    = hmm_probs.get("High Growth / High Inflation", 0.0)
                                   + hmm_probs.get("Low Growth / High Inflation", 0.0),
            pcepilfe_level         = pcepilfe_level,
            pcepilfe_zscore        = pcepilfe_zscore,
            cfnai_zscore           = cfnai_zscore,
            unrate_zscore          = unrate_zscore,
            cpiaucsl_zscore        = cpiaucsl_zscore,
            vix_level              = vix_level,
            hy_spread              = hy_spread,
            yield_curve            = yield_curve,
            gates_fired            = gates_fired,
        )

        cache_key = build_cache_key(blinded)

        # Cache hit — no LLM call needed
        if cache_key in validator_cache:
            decision_dict = validator_cache[cache_key]
            print(f"  Validator cache hit: {cache_key[:8]}… → {decision_dict['decision']}")
        else:
            # Cache miss — call LLM
            print(f"  Validator invoking LLM for {observation_date} "
                  f"(gates: {', '.join(g.split(':')[0] for g in gates_fired)})")
            try:
                llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
                messages = [
                    SystemMessage(content=SYSTEM_PROMPT),
                    HumanMessage(content=build_user_prompt(blinded)),
                ]
                response      = llm.invoke(messages)
                decision_dict = parse_validator_response(response.content)
            except Exception as e:
                print(f"  Validator LLM call failed ({e}), defaulting to CONFIRM")
                decision_dict = {
                    "decision":               "CONFIRM",
                    "replacement_regime":     None,
                    "rationale":              "",
                    "primary_contradiction":  None,
                    "confidence_in_decision": "LOW",
                    "parse_note":             f"LLM call failed: {e}",
                }

            # Contamination audit — log any markers found
            rationale  = decision_dict.get("rationale", "")
            contam     = audit_rationale_for_contamination(rationale)
            if contam:
                print(f"  WARNING contamination markers in rationale: {contam}")
            decision_dict["contamination_markers"] = contam
            decision_dict["observation_date"]      = observation_date
            decision_dict["prompt_version"]        = PROMPT_VERSION
            decision_dict["gates_fired"]           = gates_fired
            decision_dict["blinded_input_summary"] = {
                "pce_level":      blinded["pcepilfe_yoy_pct"],
                "vix":            blinded["vix"],
                "hmm_confidence": blinded["hmm_confidence"],
            }

            validator_cache[cache_key] = decision_dict
            _save_validator_cache(validator_cache)
            time.sleep(0.5)

        decision           = decision_dict["decision"]
        replacement_regime = decision_dict.get("replacement_regime")
        rationale          = decision_dict.get("rationale", "")

        # Build return dict — always write audit fields
        out: dict = {
            "original_hmm_regime":        hmm_regime,
            "regime_validator_decision":  decision,
            "regime_validator_rationale": rationale,
        }

        # In "active" mode: apply decision to regime/confidence
        if validate_regime == "active":
            if decision == "OVERRIDE" and replacement_regime:
                print(f"  Validator OVERRIDE: {hmm_regime} → {replacement_regime}")
                out["regime"] = replacement_regime
                # Recalculate growth/inflation direction from replacement
                out["inflation_direction"] = (
                    "rising" if "High Inflation" in replacement_regime else "falling"
                )
                out["growth_direction"] = (
                    "rising" if "High Growth" in replacement_regime else "falling"
                )
            elif decision == "FLAG":
                print(f"  Validator FLAG: confidence capped at 0.25 for {observation_date}")
                out["regime_confidence"] = 0.25

        return out

    # ------------------------------------------------------------------
    def quant_allocation_node(state: MacroState) -> dict:
        """Generate tactical weights via Black-Litterman."""
        observation_date = state.get("observation_date") or state["current_date"]
        regime           = state.get("regime", "Low Growth / Low Inflation")
        confidence       = state.get("regime_confidence", 0.25)

        obs_dt            = pd.Timestamp(observation_date)
        available_returns = returns_df[returns_df.index <= obs_dt].tail(COV_WINDOW_MONTHS)

        if len(available_returns) < 12:
            print(f"  BL insufficient return history for {observation_date}, using baseline")
            return {"weights": BASELINE_WEIGHTS.copy()}

        try:
            weights = generate_target_weights(available_returns, regime, confidence)
        except Exception as e:
            print(f"  BL failed for {observation_date}: {e}, using baseline")
            weights = BASELINE_WEIGHTS.copy()

        return {"weights": weights}

    # ------------------------------------------------------------------
    def narrative_generator(state: MacroState) -> dict:
        """LLM analyst node — explains the HMM regime call and BL weights."""
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

        regime             = state.get("regime", "Unknown")
        confidence         = state.get("regime_confidence", 0.0)
        weights            = state.get("weights", {})
        hmm_probs          = state.get("hmm_probabilities", {})
        macro_data         = state.get("macro_data", {})
        obs_date           = state.get("current_date", "")
        original_regime    = state.get("original_hmm_regime")
        validator_decision = state.get("regime_validator_decision", "SKIPPED")

        indicator_text = ""
        for key, val in macro_data.items():
            if isinstance(val, dict) and "error" not in val:
                indicator_text += (
                    f"\n  {key.upper()}: latest={val.get('latest')}, "
                    f"change={val.get('change')}, as_of={val.get('date')}"
                )

        weights_text = ", ".join(
            f"{asset.replace('_', ' ').title()} {w:.1%}"
            for asset, w in weights.items()
        )
        probs_text = ", ".join(f"{r}: {p:.1%}" for r, p in hmm_probs.items())

        # Build regime context — distinguish HMM call from validator override
        if (validator_decision == "OVERRIDE"
                and original_regime
                and original_regime != regime):
            regime_context = (
                f"The HMM originally classified the regime as "
                f"{original_regime} with {confidence:.1%} confidence. "
                f"The LLM validator overrode this classification to {regime} "
                f"because PCE YoY was above the Fed's 2% target while the HMM "
                f"called Low Inflation — a known structural limitation of the "
                f"rolling z-score window. The final regime used for allocation is {regime}."
            )
            task1_instruction = (
                f"Explain why the HMM originally called {original_regime} "
                f"(cite the specific indicators), then explain why the validator "
                f"correctly overrode this to {regime} (cite the PCE level vs Fed target). "
                f"Be specific about the z-score anchoring issue."
            )
        elif validator_decision == "FLAG":
            regime_context = (
                f"The HMM classified the regime as {regime} with {confidence:.1%} "
                f"confidence, but the validator flagged low conviction. "
                f"Policy weights were applied as a result."
            )
            task1_instruction = (
                f"Explain which indicators caused the HMM to call {regime} "
                f"and why the validator flagged low conviction."
            )
        else:
            regime_context = (
                f"The HMM classified the regime as {regime} "
                f"with {confidence:.1%} confidence."
            )
            task1_instruction = (
                f"Explain which specific macro indicators caused the HMM to "
                f"classify {regime} with {confidence:.1%} confidence."
            )

        system_message = """You are a quantitative macro analyst writing a concise executive
    summary for a portfolio manager.

    Your role is strictly to EXPLAIN the output of a statistical model pipeline —
    you are NOT making allocation decisions. The Hidden Markov Model (HMM) has
    already classified the regime, and the Black-Litterman optimizer has already
    calculated the weights. Your job is to explain WHY, using the macro indicators.

    Write in clear, institutional language. Be specific about which indicators
    drove the regime call. Do not suggest alternative allocations."""

        user_message = f"""Date: {obs_date}

    REGIME CLASSIFICATION:
    {regime_context}
    Joint probabilities: {probs_text}

    BLACK-LITTERMAN WEIGHTS:
    {weights_text}

    MACRO INDICATORS:
    {indicator_text}

    Task 1 — Regime Rationale (2-3 sentences):
    {task1_instruction}

    Task 2 — Allocation Rationale (2-3 sentences):
    Explain why the Black-Litterman model tilted toward the above weights
    given this regime, referencing the Bridgewater framework."""

        messages = [
            SystemMessage(content=system_message),
            HumanMessage(content=user_message),
        ]

        response  = llm.invoke(messages)
        full_text = response.content

        if "Task 2" in full_text or "Allocation Rationale" in full_text:
            parts = full_text.split("\n\n")
            mid   = len(parts) // 2
            regime_rationale     = "\n\n".join(parts[:mid]).strip()
            allocation_rationale = "\n\n".join(parts[mid:]).strip()
        else:
            regime_rationale     = full_text
            allocation_rationale = ""

        return {
            "regime_rationale":     regime_rationale,
            "allocation_rationale": allocation_rationale,
            "messages":             messages,
        }

    # ------------------------------------------------------------------
    # Wire the graph
    # ------------------------------------------------------------------
    graph_builder = StateGraph(MacroState)

    graph_builder.add_node("quant_regime_node",     quant_regime_node)
    graph_builder.add_node("quant_allocation_node", quant_allocation_node)
    graph_builder.add_node("weight_calculator",     weight_calculator)
    graph_builder.add_node("reporter",              reporter)

    if not skip_fred:
        graph_builder.add_node("data_fetcher", data_fetcher)
    if not skip_narrative:
        graph_builder.add_node("narrative_generator", narrative_generator)
    if validate_regime != "off":
        graph_builder.add_node("llm_regime_validator", llm_regime_validator)

    # Entry point
    if skip_fred:
        graph_builder.add_edge(START, "quant_regime_node")
    else:
        graph_builder.add_edge(START,          "data_fetcher")
        graph_builder.add_edge("data_fetcher", "quant_regime_node")

    # regime → [validator] → allocation
    if validate_regime != "off":
        graph_builder.add_edge("quant_regime_node",     "llm_regime_validator")
        graph_builder.add_edge("llm_regime_validator",  "quant_allocation_node")
    else:
        graph_builder.add_edge("quant_regime_node", "quant_allocation_node")

    graph_builder.add_edge("quant_allocation_node", "weight_calculator")

    if skip_narrative:
        graph_builder.add_edge("weight_calculator", "reporter")
    else:
        graph_builder.add_edge("weight_calculator",   "narrative_generator")
        graph_builder.add_edge("narrative_generator", "reporter")

    graph_builder.add_edge("reporter", END)

    return graph_builder.compile(checkpointer=memory)


# ---------------------------------------------------------------------------
# Live analysis entry point
# ---------------------------------------------------------------------------

def run_analysis(
    use_cfnai_ma3: bool = True,
    validate_regime: str = "log",
):
    """
    Live mode: fresh RegimeHMMEngine + fresh ETF returns per call.

    v4 defaults: use_cfnai_ma3=True, validate_regime="log" (advisory only).
    Pass validate_regime="active" to enable autonomous override.
    """
    fred   = Fred(api_key=os.getenv("FRED_API_KEY"))
    engine = RegimeHMMEngine(fred, use_cfnai_ma3=use_cfnai_ma3)

    tickers = list(ASSET_PROXIES.values())
    prices  = _fetch_price_history(
        tickers,
        start=(datetime.now() - timedelta(days=365 * 6)).strftime("%Y-%m-%d"),
        end=datetime.now().strftime("%Y-%m-%d"),
    )
    returns_df = prices.rename(
        columns={v: k for k, v in ASSET_PROXIES.items()}
    ).pct_change().dropna()

    graph  = build_graph(engine, returns_df, validate_regime=validate_regime)
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}

    obs_date = datetime.now().strftime("%Y-%m-%d")
    initial_state: MacroState = {
        "current_date":               obs_date,
        "observation_date":           None,
        "macro_data":                 None,
        "fetch_attempts":             0,
        "data_requests":              None,
        "growth_direction":           None,
        "inflation_direction":        None,
        "regime":                     None,
        "regime_confidence":          None,
        "regime_rationale":           None,
        "previous_regime":            None,
        "hmm_probabilities":          None,
        "original_hmm_regime":        None,
        "regime_validator_decision":  None,
        "regime_validator_rationale": None,
        "pcepilfe_level":             None,
        "tilts":                      None,
        "weights":                    None,
        "allocation_rationale":       None,
        "report":                     None,
        "messages":                   [],
        "history_dates":              None,
    }

    return graph.invoke(initial_state, config=config)


# ---------------------------------------------------------------------------
# Backtest entry point
# ---------------------------------------------------------------------------

@retry(
    wait=wait_exponential(multiplier=1, min=2, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)
def _invoke_with_retry(graph, state, config):
    return graph.invoke(state, config=config)


def run_backtest(
    start: str = "2010-01-01",
    end: Optional[str] = None,
    progress_callback=None,
    use_cfnai_ma3: bool = True,
    validate_regime: str = "off",
) -> dict:
    """
    Point-in-time backtest: weights[t] applied to returns[t+1], no look-ahead.

    v4 parameters:
        use_cfnai_ma3:   True  → Arm 1b/2/3; False → Arm 1a (v3-compatible)
        validate_regime: "off" → Arm 1 (baseline, fast)
                         "log" → Arm 2 (advisory, populates validator cache)
                         "active" → Arm 3 (active override, fast if Arm 2 ran first)

    Three-arm experiment sequence:
        run_backtest(validate_regime="off",    use_cfnai_ma3=True)  # Arm 1
        run_backtest(validate_regime="log",    use_cfnai_ma3=True)  # Arm 2
        run_backtest(validate_regime="active", use_cfnai_ma3=True)  # Arm 3
    """
    if end is None:
        end = datetime.today().strftime("%Y-%m-%d")

    observation_dates = _monthly_dates(start, end)
    n_dates           = len(observation_dates)

    all_tickers = list(ASSET_PROXIES.values())

    prices          = _fetch_price_history(all_tickers, start, end)
    monthly_returns = prices.pct_change().dropna()

    cov_start   = (datetime.strptime(start, "%Y-%m-%d") - timedelta(days=365 * 5)).strftime("%Y-%m-%d")
    prices_full = _fetch_price_history(all_tickers, cov_start, end)
    returns_df  = prices_full.rename(
        columns={v: k for k, v in ASSET_PROXIES.items()}
    ).pct_change().dropna()

    fred   = Fred(api_key=os.getenv("FRED_API_KEY"))
    engine = RegimeHMMEngine(fred, use_cfnai_ma3=use_cfnai_ma3)
    graph  = build_graph(
        engine, returns_df,
        skip_narrative=True,
        skip_fred=True,
        validate_regime=validate_regime,
    )

    monthly_records = []

    for i, obs_date in enumerate(observation_dates):
        if progress_callback:
            progress_callback(i / n_dates, f"Processing {obs_date}  ({i+1}/{n_dates})")

        config = {"configurable": {"thread_id": str(uuid.uuid4())}}

        initial_state: MacroState = {
            "current_date":               obs_date,
            "observation_date":           obs_date,
            "macro_data":                 None,
            "fetch_attempts":             0,
            "data_requests":              None,
            "growth_direction":           None,
            "inflation_direction":        None,
            "regime":                     None,
            "regime_confidence":          None,
            "regime_rationale":           None,
            "previous_regime":            None,
            "hmm_probabilities":          None,
            "original_hmm_regime":        None,
            "regime_validator_decision":  None,
            "regime_validator_rationale": None,
            "pcepilfe_level":             None,
            "tilts":                      None,
            "weights":                    None,
            "allocation_rationale":       None,
            "report":                     None,
            "messages":                   [],
            "history_dates":              observation_dates[:i + 1],
        }

        try:
            result = _invoke_with_retry(graph, initial_state, config)
        except Exception as e:
            print(f"  WARNING: {obs_date} failed permanently ({e}), using baseline weights")
            result = {
                "weights":                    BASELINE_WEIGHTS.copy(),
                "regime":                     "Unknown",
                "regime_confidence":          0.25,
                "regime_validator_decision":  "SKIPPED",
                "regime_validator_rationale": None,
                "original_hmm_regime":        None,
            }

        monthly_records.append({
            "date":               obs_date,
            "regime":             result.get("regime", "Unknown"),
            "confidence":         result.get("regime_confidence", 0.25),
            "weights":            result.get("weights", BASELINE_WEIGHTS.copy()),
            "validator_decision": result.get("regime_validator_decision", "SKIPPED"),
            "original_regime":    result.get("original_hmm_regime"),
        })

        time.sleep(1)

    if progress_callback:
        progress_callback(0.95, "Computing performance metrics...")

    result_perf = _compute_performance(monthly_records, monthly_returns)

    # Validator decision summary
    if validate_regime != "off":
        decisions = [r["validator_decision"] for r in monthly_records]
        from collections import Counter
        counts = Counter(decisions)
        print(f"\n=== Validator Decision Summary (mode={validate_regime}) ===")
        for decision, count in sorted(counts.items()):
            print(f"  {decision:<10} {count:>4} months")
        overrides = [r for r in monthly_records if r["validator_decision"] == "OVERRIDE"]
        if overrides:
            print(f"\n  OVERRIDE details:")
            vc = _load_validator_cache()
            for r in overrides:
                # Find cache entry by observation_date
                replacement = next(
                    (v.get("replacement_regime") for v in vc.values()
                    if v.get("observation_date") == r["date"]),
                    "unknown"
                )
                print(f"    {r['date']}  {r['original_regime']} → {replacement}")

    # Average weights by regime
    regime_weights = defaultdict(list)
    for record in monthly_records:
        regime_weights[record["regime"]].append(record["weights"])

    print("\n=== Average Weights by Regime ===")
    for regime, weight_list in sorted(regime_weights.items()):
        avg = {k: np.mean([w.get(k, 0.0) for w in weight_list]) for k in BASELINE_WEIGHTS}
        n   = len(weight_list)
        print(f"\n{regime} (n={n} months):")
        for asset, w in avg.items():
            bar = "█" * int(w * 40)
            print(f"  {asset:<22} {w:>6.1%}  {bar}")

    if progress_callback:
        progress_callback(1.0, "Done.")

    return {
        "equity_curve":    result_perf["equity_curve"],
        "benchmark_curve": result_perf["benchmark_curve"],
        "policy_curve":    result_perf["policy_curve"],
        "monthly_records": monthly_records,
        "metrics":         result_perf["metrics"],
    }


if __name__ == "__main__":
    result = run_analysis()
    print(result.get("report", "No report generated"))