"""
macro_lens.py — LangGraph orchestration pipeline for macro-lens v3.

Architecture (v3 hybrid quant/AI):
  data_fetcher        → fetches FRED indicators + VIX for live display
  quant_regime_node   → RegimeHMMEngine classifies growth/inflation regime
  quant_allocation_node → Black-Litterman generates tactical weights
  weight_calculator   → normalises weights to sum to 1.0 (safety net)
  narrative_generator → LLM writes human-readable rationale (live mode only)
  reporter            → formats the final report string

The LLM's role in v3 is strictly explanatory — it reads the HMM regime call
and BL weights and explains why the quant models produced them. All allocation
decisions are made by the HMM + BL layer; the LLM cannot override them.

Two execution modes:
  Live (run_analysis):    full pipeline including FRED fetch + LLM narrative
  Backtest (run_backtest): skip_fred=True, skip_narrative=True for speed;
                           weights[t] applied to returns[t+1] (no look-ahead)

Benchmarks computed in run_backtest:
  60/40:      60% SPY + 40% TLT — standard equity/bond reference
  Policy mix: static 40/30/10/8/7/5 monthly-rebalanced — the correct primary
              benchmark for a TAA overlay; isolates regime-overlay alpha from
              strategic asset mix choice. Information Ratio vs policy mix is
              the key performance metric.
"""

import socket
socket.setdefaulttimeout(10)

import os
from fredapi import Fred
import yfinance as yf
import pandas as pd
from dotenv import load_dotenv

from typing import Annotated, Optional, Dict, Any, List
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from datetime import datetime, timedelta

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

import time
import uuid
import concurrent.futures
from collections import defaultdict
import numpy as np
from tenacity import retry, wait_exponential, stop_after_attempt

from hmm_models import RegimeHMMEngine
from black_litterman import generate_target_weights, ASSETS as BL_ASSETS

load_dotenv(override=True)


# LangGraph state schema

class MacroState(TypedDict):
    # Meta
    current_date: str
    observation_date: Optional[str]

    # FRED indicators (live mode only; None in backtest)
    macro_data: Optional[Dict[str, Any]]
    fetch_attempts: int
    data_requests: Optional[List[str]]

    # Regime — classified by HMM (not LLM)
    growth_direction: Optional[str]
    inflation_direction: Optional[str]
    regime: Optional[str]
    regime_confidence: Optional[float]          # float [0,1]
    regime_rationale: Optional[str]
    previous_regime: Optional[str]
    hmm_probabilities: Optional[Dict[str, float]]

    # Allocation — generated by BL (not LLM)
    tilts: Optional[Dict[str, str]]             # kept for reporter compatibility
    weights: Optional[Dict[str, float]]
    allocation_rationale: Optional[str]

    # Output
    report: Optional[str]
    messages: Annotated[List[Any], add_messages]

    # Backtest bookkeeping
    history_dates: Optional[List[str]]


# FRED series for live dashboard display

# Primary series fetched on every live run
PRIMARY_SERIES = {
    "t10y2y":       "T10Y2Y",        # yield curve slope
    "bamlh0a0hym2": "BAMLH0A0HYM2",  # HY credit spread
    "t10yie":       "T10YIE",         # 10y breakeven inflation
    "pcepilfe":     "PCEPILFE",       # core PCE (primary inflation HMM feature)
    "cfnai":        "CFNAI",          # Chicago Fed activity index (primary growth HMM feature)
    "sahmrealtime": "SAHMREALTIME",   # Sahm rule recession indicator
    "unrate":       "UNRATE",         # unemployment rate
    "stlfsi4":      "STLFSI4",        # St Louis financial stress index
}

# Secondary series fetched on retry (fetch_attempts > 0)
SECONDARY_SERIES = {
    "cpiaucsl": "CPIAUCSL",   # CPI (secondary inflation HMM feature)
    "permit":   "PERMIT",     # building permits (leading indicator)
    "umcsent":  "UMCSENT",    # U Michigan consumer sentiment
}


# ETF proxies and policy weights

ASSET_PROXIES = {
    "equities":         "SPY",
    "bonds":            "TLT",
    "inflation_linked": "TIP",
    "commodities":      "GSG",
    "gold":             "GLD",
    "cash":             "BIL",
}

# Policy weights — the TAA strategy's neutral allocation.
# Doubles as the BL prior anchor and the primary backtest benchmark.
BASELINE_WEIGHTS = {
    "equities":         0.40,
    "bonds":            0.30,
    "inflation_linked": 0.10,
    "commodities":      0.08,
    "gold":             0.07,
    "cash":             0.05,
}

# Trailing window for BL covariance matrix estimation
COV_WINDOW_MONTHS = 60


# FRED fetch helpers

def fetch_fred_series(fred: Fred, series_id: str, observation_date: Optional[str] = None) -> dict:
    """
    Fetch the latest value of a FRED series for live dashboard display.

    Uses ALFRED realtime parameters when observation_date is provided
    (backtest mode) to avoid look-ahead bias. In live mode, fetches the
    most recent published value.

    Returns a dict with keys: latest, previous, change, date.
    On error, returns {"error": <message>}.
    """
    try:
        def _fetch():
            if observation_date:
                start_date = (
                    datetime.strptime(observation_date, "%Y-%m-%d") - timedelta(days=365)
                ).strftime("%Y-%m-%d")
                return fred.get_series(
                    series_id,
                    observation_start=start_date,
                    observation_end=observation_date,
                    realtime_start=observation_date,
                    realtime_end=observation_date,
                )
            else:
                start_date = (datetime.now() - timedelta(days=365)).strftime("%Y-%m-%d")
                return fred.get_series(series_id, observation_start=start_date)

        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_fetch)
            data = future.result(timeout=15)

        data = data.dropna()
        if len(data) == 0:
            return {"error": "no data"}

        latest   = float(data.iloc[-1])
        previous = float(data.iloc[-2]) if len(data) >= 2 else None
        mom_change = round(latest - previous, 4) if previous is not None else None

        return {
            "latest":   round(latest, 4),
            "previous": round(previous, 4) if previous else None,
            "change":   mom_change,
            "date":     str(data.index[-1].date()),
        }
    except concurrent.futures.TimeoutError:
        return {"error": f"timeout fetching {series_id}"}
    except Exception as e:
        return {"error": str(e)}


def fetch_vix(observation_date: Optional[str] = None) -> dict:
    """Fetch VIX closing price via yfinance for live dashboard display."""
    try:
        vix = yf.Ticker("^VIX")
        if observation_date:
            end_dt   = datetime.strptime(observation_date, "%Y-%m-%d")
            start_dt = end_dt - timedelta(days=10)
            hist = vix.history(
                start=start_dt.strftime("%Y-%m-%d"),
                end=(end_dt + timedelta(days=1)).strftime("%Y-%m-%d"),
            )
        else:
            hist = vix.history(period="5d")

        if hist.empty:
            return {"error": "no data"}

        latest   = round(float(hist["Close"].iloc[-1]), 2)
        previous = round(float(hist["Close"].iloc[-2]), 2) if len(hist) >= 2 else None
        return {
            "latest":   latest,
            "previous": previous,
            "change":   round(latest - previous, 2) if previous else None,
            "date":     str(hist.index[-1].date()),
        }
    except Exception as e:
        return {"error": str(e)}


def data_fetcher(state: MacroState) -> dict:
    """LangGraph node: fetch FRED indicators and VIX for live dashboard."""
    fred = Fred(api_key=os.getenv("FRED_API_KEY"))
    fetch_attempts   = state.get("fetch_attempts", 0)
    observation_date = state.get("observation_date")

    series_to_fetch = PRIMARY_SERIES.copy()
    if fetch_attempts > 0:
        series_to_fetch.update(SECONDARY_SERIES)

    macro_data = {}
    for key, series_id in series_to_fetch.items():
        macro_data[key] = fetch_fred_series(fred, series_id, observation_date)

    macro_data["vix"] = fetch_vix(observation_date)

    return {
        "macro_data":    macro_data,
        "fetch_attempts": fetch_attempts + 1,
    }


# ETF price helpers

def _fetch_price_history(tickers: List[str], start: str, end: str) -> pd.DataFrame:
    """Download monthly ETF price history via yfinance."""
    raw = yf.download(
        tickers,
        start=start,
        end=(datetime.strptime(end, "%Y-%m-%d") + timedelta(days=5)).strftime("%Y-%m-%d"),
        interval="1mo",
        auto_adjust=True,
        progress=False,
    )
    if isinstance(raw.columns, pd.MultiIndex):
        prices = raw["Close"]
    else:
        prices = raw[["Close"]] if "Close" in raw.columns else raw

    return prices.ffill().dropna(how="all")


def _monthly_dates(start: str = "2010-01-01", end: Optional[str] = None) -> List[str]:
    """Generate month-end dates between start and end (inclusive)."""
    start_dt = datetime.strptime(start, "%Y-%m-%d")
    end_dt   = datetime.strptime(end, "%Y-%m-%d") if end else datetime.today()

    dates   = []
    current = start_dt.replace(day=1)
    while current <= end_dt:
        if current.month == 12:
            last_day = current.replace(day=31)
        else:
            last_day = current.replace(month=current.month + 1, day=1) - timedelta(days=1)
        if last_day > end_dt:
            last_day = end_dt
        dates.append(last_day.strftime("%Y-%m-%d"))
        if current.month == 12:
            current = current.replace(year=current.year + 1, month=1)
        else:
            current = current.replace(month=current.month + 1)

    return dates


# Performance computation

def _compute_performance(monthly_records: list, monthly_returns: pd.DataFrame) -> dict:
    """
    Compute equity curves and metrics for three series:
      - Macro-Lens portfolio (regime-driven BL weights)
      - Policy mix (static 40/30/10/8/7/5, monthly rebalanced)
      - 60/40 benchmark (60% SPY + 40% TLT)

    Weights at time t are applied to returns at time t+1 (no look-ahead).
    The policy mix is the primary benchmark — it isolates regime-overlay
    alpha from the choice of strategic asset mix.
    """
    portfolio_returns = []
    benchmark_returns = []
    policy_returns    = []
    perf_dates        = []

    policy_w = {"SPY": 0.40, "TLT": 0.30, "TIP": 0.10,
                "GSG": 0.08, "GLD": 0.07, "BIL": 0.05}

    for i, record in enumerate(monthly_records[:-1]):
        next_date_str = monthly_records[i + 1]["date"]
        next_dt       = pd.Timestamp(next_date_str)

        ret_idx = monthly_returns.index
        mask    = (ret_idx.year == next_dt.year) & (ret_idx.month == next_dt.month)
        if not mask.any():
            continue

        ret_row = monthly_returns[mask].iloc[0]
        w       = record["weights"]

        # Macro-Lens portfolio return
        port_ret = sum(
            w.get(asset, 0.0) * float(ret_row[ticker])
            for asset, ticker in ASSET_PROXIES.items()
            if ticker in ret_row.index and not pd.isna(ret_row[ticker])
        )

        # 60/40 benchmark return
        spy_ret   = float(ret_row["SPY"]) if "SPY" in ret_row.index and not pd.isna(ret_row["SPY"]) else 0.0
        tlt_ret   = float(ret_row["TLT"]) if "TLT" in ret_row.index and not pd.isna(ret_row["TLT"]) else 0.0
        bench_ret = 0.60 * spy_ret + 0.40 * tlt_ret

        # Policy mix return
        pol_ret = sum(
            pw * float(ret_row[ticker])
            for ticker, pw in policy_w.items()
            if ticker in ret_row.index and not pd.isna(ret_row[ticker])
        )

        portfolio_returns.append(port_ret)
        benchmark_returns.append(bench_ret)
        policy_returns.append(pol_ret)
        perf_dates.append(next_dt)

    port_series   = pd.Series(portfolio_returns, index=perf_dates)
    bench_series  = pd.Series(benchmark_returns, index=perf_dates)
    policy_series = pd.Series(policy_returns,    index=perf_dates)

    equity_curve   = (1 + port_series).cumprod()   * 100
    benchmark_curve = (1 + bench_series).cumprod() * 100
    policy_curve    = (1 + policy_series).cumprod() * 100

    def max_drawdown(curve: pd.Series) -> float:
        rolling_max = curve.cummax()
        return float(((curve - rolling_max) / rolling_max).min())

    def sharpe(returns: pd.Series, rf: float = 0.02) -> float:
        ann_ret = (1 + returns.mean()) ** 12 - 1
        ann_vol = returns.std() * (12 ** 0.5)
        return (ann_ret - rf) / ann_vol if ann_vol > 0 else float("nan")

    n_months = len(port_series)
    n_years  = n_months / 12 if n_months > 0 else 1

    total_ret_port   = float((equity_curve.iloc[-1]   / 100) - 1)
    total_ret_bench  = float((benchmark_curve.iloc[-1] / 100) - 1)
    total_ret_policy = float((policy_curve.iloc[-1]    / 100) - 1)

    print("\n=== Benchmark Comparison ===")
    print(f"{'Metric':<25} {'Macro-Lens':>12} {'Policy Mix':>12} {'60/40':>12}")
    print("-" * 63)
    print(f"{'Total Return':<25} {total_ret_port:>11.1%} {total_ret_policy:>11.1%} {total_ret_bench:>11.1%}")
    print(f"{'Ann. Return':<25} {float((1+total_ret_port)**(1/n_years)-1):>11.1%} "
          f"{float((1+total_ret_policy)**(1/n_years)-1):>11.1%} "
          f"{float((1+total_ret_bench)**(1/n_years)-1):>11.1%}")
    print(f"{'Sharpe':<25} {sharpe(port_series):>12.2f} {sharpe(policy_series):>12.2f} {sharpe(bench_series):>12.2f}")
    print(f"{'Max Drawdown':<25} {max_drawdown(equity_curve):>11.1%} "
          f"{max_drawdown(policy_curve):>11.1%} "
          f"{max_drawdown(benchmark_curve):>11.1%}")
    print(f"{'Info Ratio vs Policy':<25} {sharpe(port_series - policy_series):>12.2f}")

    return {
        "equity_curve":    equity_curve,
        "benchmark_curve": benchmark_curve,
        "policy_curve":    policy_curve,
        "metrics": {
            "sharpe_portfolio":        sharpe(port_series),
            "sharpe_benchmark":        sharpe(bench_series),
            "sharpe_policy":           sharpe(policy_series),
            "max_drawdown_portfolio":  max_drawdown(equity_curve),
            "max_drawdown_benchmark":  max_drawdown(benchmark_curve),
            "max_drawdown_policy":     max_drawdown(policy_curve),
            "total_return_portfolio":  total_ret_port,
            "total_return_benchmark":  total_ret_bench,
            "total_return_policy":     total_ret_policy,
            "ann_return_portfolio":    float((1 + total_ret_port)  ** (1 / n_years) - 1),
            "ann_return_benchmark":    float((1 + total_ret_bench) ** (1 / n_years) - 1),
            "ann_return_policy":       float((1 + total_ret_policy) ** (1 / n_years) - 1),
            "n_months":                n_months,
        },
    }


# LangGraph nodes

def weight_calculator(state: MacroState) -> dict:
    """
    Normalise BL weights to exactly 1.0.

    BL already guarantees sum=1 and long-only, but floating-point
    accumulation can produce tiny deviations. This node is a safety net
    and also handles the fallback path where BL returns BASELINE_WEIGHTS.
    """
    weights = state.get("weights", {})
    if not weights:
        return {"weights": BASELINE_WEIGHTS.copy()}

    weights = {k: max(0.0, v) for k, v in weights.items()}
    total   = sum(weights.values())
    if total <= 0:
        return {"weights": BASELINE_WEIGHTS.copy()}

    weights  = {k: round(v / total, 4) for k, v in weights.items()}
    residual = round(1.0 - sum(weights.values()), 4)
    if residual != 0.0:
        largest = max(weights, key=weights.get)
        weights[largest] = round(weights[largest] + residual, 4)

    return {"weights": weights}


def reporter(state: MacroState) -> dict:
    """LangGraph node: format the final regime report string."""
    weights   = state.get("weights", {})
    hmm_probs = state.get("hmm_probabilities", {})

    weights_text = "\n".join(
        f"  {asset.replace('_', ' ').title():<22} {weight:.1%}"
        for asset, weight in weights.items()
    )

    macro_data = state.get("macro_data") or {}

    def safe_ind(name: str, key: str) -> str:
        if not macro_data:
            return f"  {name:<25} [Not fetched in backtest mode]"
        data = macro_data.get(key, {})
        if "error" in data:
            return f"  {name:<25} [Fetch Error/Unavailable]"
        latest     = data.get("latest")
        change     = data.get("change")
        latest_str = f"{latest:>8.2f}" if latest is not None else "     N/A"
        change_str = f"{change:>+.2f}" if change is not None else " N/A"
        return f"  {name:<25} {latest_str}  (chg: {change_str})"

    probs_text = "\n".join(
        f"  {regime:<35} {prob:.1%}"
        for regime, prob in hmm_probs.items()
    ) if hmm_probs else "  N/A"

    report = f"""
╔══════════════════════════════════════════════════════╗
║           MACRO-LENS REGIME REPORT  (v3)             ║
║           {state['current_date']:<42} ║
╚══════════════════════════════════════════════════════╝

MACRO REGIME  [HMM]
────────────
Regime:      {state.get('regime', 'Unknown')}
Growth:      {str(state.get('growth_direction')).title()}
Inflation:   {str(state.get('inflation_direction')).title()}
Confidence:  {state.get('regime_confidence', 0.0):.1%}

JOINT REGIME PROBABILITIES
──────────────────────────
{probs_text}

REGIME RATIONALE  [LLM Analyst]
────────────────
{state.get('regime_rationale', 'N/A')}

KEY INDICATORS
──────────────
{safe_ind('Yield curve (T10Y2Y)', 't10y2y')}
{safe_ind('HY spread (BAMLH)', 'bamlh0a0hym2')}
{safe_ind('Breakeven inf (T10YIE)', 't10yie')}
{safe_ind('Core PCE', 'pcepilfe')}
{safe_ind('CFNAI (activity index)', 'cfnai')}
{safe_ind('Sahm rule', 'sahmrealtime')}
{safe_ind('VIX', 'vix')}

TACTICAL ALLOCATION  [Black-Litterman]
───────────────────
{weights_text}

ALLOCATION RATIONALE  [LLM Analyst]
────────────────────
{state.get('allocation_rationale', 'N/A')}
""".strip()

    return {"report": report}


# LangGraph pipeline factory

def build_graph(
    engine: RegimeHMMEngine,
    returns_df: pd.DataFrame,
    skip_narrative: bool = False,
    skip_fred: bool = False,
):
    """
    Build and compile the LangGraph pipeline.

    Accepts a pre-instantiated RegimeHMMEngine and a pre-fetched returns
    DataFrame so that:
      - Each execution context gets its own engine instance — no shared
        mutable state between concurrent Gradio users.
      - ETF returns are fetched once per run, not once per month.

    Nodes are closures over engine and returns_df.

    Graph topology:
      Live:     data_fetcher → quant_regime_node → quant_allocation_node
                → weight_calculator → narrative_generator → reporter
      Backtest: quant_regime_node → quant_allocation_node
                → weight_calculator → reporter
    """
    memory = MemorySaver()

    def quant_regime_node(state: MacroState) -> dict:
        """Classify the macro regime via RegimeHMMEngine."""
        observation_date = state.get("observation_date") or state["current_date"]

        try:
            result = engine.infer(observation_date)
        except ValueError as e:
            # Insufficient history — return uniform prior (early backtest dates)
            print(f"  HMM insufficient history for {observation_date}: {e}")
            return {
                "regime":            "Low Growth / Low Inflation",
                "regime_confidence": 0.25,
                "growth_direction":  "falling",
                "inflation_direction": "falling",
                "hmm_probabilities": {
                    "High Growth / High Inflation": 0.25,
                    "High Growth / Low Inflation":  0.25,
                    "Low Growth / High Inflation":  0.25,
                    "Low Growth / Low Inflation":   0.25,
                },
            }

        if "error" in result:
            print(f"  HMM error for {observation_date}: {result['error']}")
            return {
                "regime":            "Low Growth / Low Inflation",
                "regime_confidence": 0.25,
                "growth_direction":  "falling",
                "inflation_direction": "falling",
                "hmm_probabilities": {},
            }

        dominant    = result["dominant_regime"]
        confidence  = result["confidence"]
        joint_probs = result["joint_probabilities"]

        return {
            "regime":               dominant,
            "regime_confidence":    confidence,
            "growth_direction":     "rising" if result["growth_high_prob"] >= 0.5 else "falling",
            "inflation_direction":  "rising" if result["inflation_high_prob"] >= 0.5 else "falling",
            "hmm_probabilities":    joint_probs,
            "previous_regime":      dominant,
        }

    def quant_allocation_node(state: MacroState) -> dict:
        """Generate tactical weights via Black-Litterman."""
        observation_date = state.get("observation_date") or state["current_date"]
        regime           = state.get("regime", "Low Growth / Low Inflation")
        confidence       = state.get("regime_confidence", 0.25)

        obs_dt            = pd.Timestamp(observation_date)
        available_returns = returns_df[returns_df.index <= obs_dt].tail(COV_WINDOW_MONTHS)

        if len(available_returns) < 12:
            print(f"  BL insufficient return history for {observation_date}, using baseline")
            return {"weights": BASELINE_WEIGHTS.copy()}

        try:
            weights = generate_target_weights(available_returns, regime, confidence)
        except Exception as e:
            print(f"  BL failed for {observation_date}: {e}, using baseline")
            weights = BASELINE_WEIGHTS.copy()

        return {"weights": weights}

    def narrative_generator(state: MacroState) -> dict:
        """
        LLM analyst node — explains the HMM regime call and BL weights.
        Does NOT make allocation decisions; strictly explanatory.
        """
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

        regime     = state.get("regime", "Unknown")
        confidence = state.get("regime_confidence", 0.0)
        weights    = state.get("weights", {})
        hmm_probs  = state.get("hmm_probabilities", {})
        macro_data = state.get("macro_data", {})
        obs_date   = state.get("current_date", "")

        indicator_text = ""
        for key, val in macro_data.items():
            if isinstance(val, dict) and "error" not in val:
                indicator_text += (
                    f"\n  {key.upper()}: latest={val.get('latest')}, "
                    f"change={val.get('change')}, as_of={val.get('date')}"
                )

        weights_text = ", ".join(
            f"{asset.replace('_', ' ').title()} {w:.1%}"
            for asset, w in weights.items()
        )
        probs_text = ", ".join(f"{r}: {p:.1%}" for r, p in hmm_probs.items())

        system_message = """You are a quantitative macro analyst writing a concise executive
summary for a portfolio manager.

Your role is strictly to EXPLAIN the output of a statistical model pipeline —
you are NOT making allocation decisions. The Hidden Markov Model (HMM) has
already classified the regime, and the Black-Litterman optimizer has already
calculated the weights. Your job is to explain WHY, using the macro indicators.

Write in clear, institutional language. Be specific about which indicators
drove the regime call. Do not suggest alternative allocations."""

        user_message = f"""Date: {obs_date}

HMM REGIME OUTPUT:
  Dominant regime: {regime}
  Confidence: {confidence:.1%}
  Joint probabilities: {probs_text}

BLACK-LITTERMAN WEIGHTS:
  {weights_text}

MACRO INDICATORS:
{indicator_text}

Task 1 — Regime Rationale (2-3 sentences):
Explain which specific macro indicators caused the HMM to classify
{regime} with {confidence:.1%} confidence.

Task 2 — Allocation Rationale (2-3 sentences):
Explain why the Black-Litterman model tilted toward the above weights
given this regime, referencing the Bridgewater framework."""

        messages = [
            SystemMessage(content=system_message),
            HumanMessage(content=user_message),
        ]

        response  = llm.invoke(messages)
        full_text = response.content

        if "Task 2" in full_text or "Allocation Rationale" in full_text:
            parts = full_text.split("\n\n")
            mid   = len(parts) // 2
            regime_rationale     = "\n\n".join(parts[:mid]).strip()
            allocation_rationale = "\n\n".join(parts[mid:]).strip()
        else:
            regime_rationale     = full_text
            allocation_rationale = ""

        return {
            "regime_rationale":     regime_rationale,
            "allocation_rationale": allocation_rationale,
            "messages":             messages,
        }

    # Wire the graph
    graph_builder = StateGraph(MacroState)

    graph_builder.add_node("quant_regime_node",     quant_regime_node)
    graph_builder.add_node("quant_allocation_node", quant_allocation_node)
    graph_builder.add_node("weight_calculator",     weight_calculator)
    graph_builder.add_node("reporter",              reporter)

    if not skip_fred:
        graph_builder.add_node("data_fetcher", data_fetcher)
    if not skip_narrative:
        graph_builder.add_node("narrative_generator", narrative_generator)

    if skip_fred:
        graph_builder.add_edge(START, "quant_regime_node")
    else:
        graph_builder.add_edge(START,          "data_fetcher")
        graph_builder.add_edge("data_fetcher", "quant_regime_node")

    graph_builder.add_edge("quant_regime_node",     "quant_allocation_node")
    graph_builder.add_edge("quant_allocation_node", "weight_calculator")

    if skip_narrative:
        graph_builder.add_edge("weight_calculator", "reporter")
    else:
        graph_builder.add_edge("weight_calculator",   "narrative_generator")
        graph_builder.add_edge("narrative_generator", "reporter")

    graph_builder.add_edge("reporter", END)

    return graph_builder.compile(checkpointer=memory)


# Live analysis entry point

def run_analysis():
    """
    Live mode: fresh RegimeHMMEngine + fresh ETF returns per call.
    Prevents state bleed between concurrent Gradio users.
    """
    fred   = Fred(api_key=os.getenv("FRED_API_KEY"))
    engine = RegimeHMMEngine(fred)

    tickers = list(ASSET_PROXIES.values())
    prices  = _fetch_price_history(
        tickers,
        start=(datetime.now() - timedelta(days=365 * 6)).strftime("%Y-%m-%d"),
        end=datetime.now().strftime("%Y-%m-%d"),
    )
    returns_df = prices.rename(
        columns={v: k for k, v in ASSET_PROXIES.items()}
    ).pct_change().dropna()

    graph  = build_graph(engine, returns_df)
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}

    obs_date = datetime.now().strftime("%Y-%m-%d")
    initial_state: MacroState = {
        "current_date":         obs_date,
        "observation_date":     None,
        "macro_data":           None,
        "fetch_attempts":       0,
        "data_requests":        None,
        "growth_direction":     None,
        "inflation_direction":  None,
        "regime":               None,
        "regime_confidence":    None,
        "regime_rationale":     None,
        "previous_regime":      None,
        "hmm_probabilities":    None,
        "tilts":                None,
        "weights":              None,
        "allocation_rationale": None,
        "report":               None,
        "messages":             [],
        "history_dates":        None,
    }

    return graph.invoke(initial_state, config=config)


# Backtest entry point

@retry(
    wait=wait_exponential(multiplier=1, min=2, max=10),
    stop=stop_after_attempt(3),
    reraise=True,
)
def _invoke_with_retry(graph, state, config):
    return graph.invoke(state, config=config)


def run_backtest(
    start: str = "2010-01-01",
    end: Optional[str] = None,
    progress_callback=None,
) -> dict:
    """
    Point-in-time backtest: weights[t] applied to returns[t+1], no look-ahead.

    Architecture:
      - One RegimeHMMEngine per run: reuses z-score cache and quarterly
        refit cadence across all monthly iterations.
      - ETF returns fetched once upfront, sliced per month in
        quant_allocation_node to enforce point-in-time covariance.
      - BL covariance window requires 60m of pre-backtest history;
        a separate price fetch covers (start - 5y) → end.

    Returns dict with equity_curve, benchmark_curve, policy_curve,
    monthly_records, and metrics.
    """
    if end is None:
        end = datetime.today().strftime("%Y-%m-%d")

    observation_dates = _monthly_dates(start, end)
    n_dates           = len(observation_dates)

    all_tickers = list(ASSET_PROXIES.values())

    # Performance calculation: prices over backtest window only
    prices          = _fetch_price_history(all_tickers, start, end)
    monthly_returns = prices.pct_change().dropna()

    # BL covariance: needs 60m pre-history so early months aren't data-starved
    cov_start  = (datetime.strptime(start, "%Y-%m-%d") - timedelta(days=365 * 5)).strftime("%Y-%m-%d")
    prices_full = _fetch_price_history(all_tickers, cov_start, end)
    returns_df  = prices_full.rename(
        columns={v: k for k, v in ASSET_PROXIES.items()}
    ).pct_change().dropna()

    fred   = Fred(api_key=os.getenv("FRED_API_KEY"))
    engine = RegimeHMMEngine(fred)
    graph  = build_graph(engine, returns_df, skip_narrative=True, skip_fred=True)

    monthly_records = []

    for i, obs_date in enumerate(observation_dates):
        if progress_callback:
            progress_callback(i / n_dates, f"Processing {obs_date}  ({i+1}/{n_dates})")

        config = {"configurable": {"thread_id": str(uuid.uuid4())}}

        initial_state: MacroState = {
            "current_date":         obs_date,
            "observation_date":     obs_date,
            "macro_data":           None,
            "fetch_attempts":       0,
            "data_requests":        None,
            "growth_direction":     None,
            "inflation_direction":  None,
            "regime":               None,
            "regime_confidence":    None,
            "regime_rationale":     None,
            "previous_regime":      None,
            "hmm_probabilities":    None,
            "tilts":                None,
            "weights":              None,
            "allocation_rationale": None,
            "report":               None,
            "messages":             [],
            "history_dates":        observation_dates[:i + 1],
        }

        try:
            result = _invoke_with_retry(graph, initial_state, config)
        except Exception as e:
            print(f"  WARNING: {obs_date} failed permanently ({e}), using baseline weights")
            result = {
                "weights":           BASELINE_WEIGHTS.copy(),
                "regime":            "Unknown",
                "regime_confidence": 0.25,
            }

        monthly_records.append({
            "date":       obs_date,
            "regime":     result.get("regime", "Unknown"),
            "confidence": result.get("regime_confidence", 0.25),
            "weights":    result.get("weights", BASELINE_WEIGHTS.copy()),
        })

        time.sleep(1)

    if progress_callback:
        progress_callback(0.95, "Computing performance metrics...")

    result_perf = _compute_performance(monthly_records, monthly_returns)

    # Average weights by regime — printed for diagnostic transparency
    regime_weights = defaultdict(list)
    for record in monthly_records:
        regime_weights[record["regime"]].append(record["weights"])

    print("\n=== Average Weights by Regime ===")
    for regime, weight_list in sorted(regime_weights.items()):
        avg = {k: np.mean([w.get(k, 0.0) for w in weight_list]) for k in BASELINE_WEIGHTS}
        n   = len(weight_list)
        print(f"\n{regime} (n={n} months):")
        for asset, w in avg.items():
            bar = "█" * int(w * 40)
            print(f"  {asset:<22} {w:>6.1%}  {bar}")

    if progress_callback:
        progress_callback(1.0, "Done.")

    return {
        "equity_curve":    result_perf["equity_curve"],
        "benchmark_curve": result_perf["benchmark_curve"],
        "policy_curve":    result_perf["policy_curve"],
        "monthly_records": monthly_records,
        "metrics":         result_perf["metrics"],
    }


if __name__ == "__main__":
    result = run_analysis()
    print(result.get("report", "No report generated"))